variables:
  DOCKER_IMAGE: ${CI_REGISTRY}/sabz-hobbies/avalon-bot
  PYTHON_VERSION: '3.9'
  DEBIAN_VERSION: bullseye


build docker image:
  stage: build
  tags: [ docker ]
  rules:
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'
  variables:
    GIT_DEPTH: 500
  script:
    - |
        make docker REGISTRY=${CI_REGISTRY} DOCKER_USER=${CI_REGISTRY_USER} DOCKER_PASS=${CI_REGISTRY_PASSWORD} \
        PYTHON_VERSION=${PYTHON_VERSION} DEBIAN_VERSION=${DEBIAN_VERSION}

kubit deploy:
  stage: deploy
  image: ${BUILD_ARG__DOCKER_REGISTRY}/sabzco/sabz-cli
  rules:
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - 'curl -X POST -F DOCKER_TAG=${DOCKER_TAG} -H "Authorization: Bearer ${KUBIT_WEBHOOK_TOKEN}" https://api.kubit.ir/api/core/packs/inp7nfdr/vars/'
